### ISSUE TITLE
Arbiter UI

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox-arbiter#21]
Hi, 

Would it be possible to add a simple UI to the arbiter? Just something that lists all the permissions granted would very useful for debugging. 

https://databox-arbiter/ui --> formatted HTML output of permmissions

Cheers

Tosh

**Comment by yousefamar** [comment]
Definitely! Would save us constantly diving into logs. I'm on it!

Post-v0.1, if we do client-side UIs that connect directly to stores (in and of itself an endeavour) then we could have the arbiter maintain a tiny store with a JSON document of all permissions, that would have all the usual logging and access controls. But for now, an arbiter UI would save us a lot of time, I agree.

**Comment by Toshbrown** [comment]
Just thinking about having to debug 40 of these things ;-(
